<?php 

$this->headLink()->appendStylesheet($this->baseUrl().'/styles/site.css');
$this->headScript()->appendFile($this->baseUrl().'/scripts/auth/login.js');

?>


<!-- SPACING -->
<div style="height: 100px;"></div>
<!-- SPACING -->

<form action="<?php echo $this->baseUrl?>/auth/login" method="post" onsubmit="return checkData();">

  <fieldset style="width: 340px;">
    <!--
      <img border="0" src="<?php echo $this->baeUrl?>/images/login.jpg" alt="Sistema de Controle Bovino"/><br/>
    -->
    <b>[Login]</b>
    <hr width="75%"/>
<?php if (!empty($this->message)):?>
    <div id="message"><font color="red"><?php echo $this->message?></font></div>
    <hr width="75%"/>
<?php endif;?>
    <legend><font size="4"><b>ACESSO RESTRITO:</b></font></legend>

	<table>

	  <tr>
	    <td align="right">Usu&aacute;rio:</td>
	    <td align="left"><input type="text" name="username" value="" style="width: 128px;"/></td>
	  </tr>

	  <tr>
	    <td align="right">Senha:</td>
	    <td align="left"><input type="password" name="password" value="" style="width: 128px;"/></td>
	  </tr>

	  <tr>
	    <td>&nbsp;</td>
	    <td style="font-size: 12px;"><input type="checkbox" name="rememberme" value="1"/>Lembrar meus dados.</td>
	  </tr>
	  <tr>
	    <td align="right" colspan="2"><input class="button" type="submit" name="login" value="ACESSAR"/></td>
	  </tr>

	</table>

  </fieldset>

</form>



<script type="text/javascript">
    document.forms[0].username.focus();
</script>



