<?php

$this->javascript();

//$this->headScript()
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.core.js')
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.tabs.js')
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.draggable.js')
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.dialog.js')
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.resizable.js')
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.qtip.js')
//	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.flexigrid.js')
//	;
//
//$this->headLink()
//	->appendStylesheet($this->baseUrl() . '/styles/flexigrid.css')
//	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.core.css')
//	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.datepicker.css')
//	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.theme.css')
//	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.tabs.css')
//	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.dialog.css')
//	;

echo $this->FormEdit($this->form, $this->baseUrl(), $this->elements);
?>
