<?php

//echo $this->FormEdit($this->form, $this->baseUrl(), $this->elements);
//echo $this->form;

$this->javascript();

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.core.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.tabs.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.draggable.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.dialog.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.resizable.js')
//	->appendFile($this->baseUrl() . '/scripts/library/genealogia.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.qtip.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.flexigrid.js')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/flexigrid.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.core.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.datepicker.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.theme.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.tabs.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.dialog.css')
	;

?>


<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getId();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">
<?=$this->form->id->removeDecorator('tag')->removeDecorator('label');?>
<table
	id="form"
	align="center"
	border="2"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('/congado/public/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="8" height="20" width="480" style="font-size: 11px;"><b><?=str_replace('_', ' ', strtoupper($this->form->getName()));?></b></td>
  </tr>

  <tr>
    <td height="2" bgcolor="#f36400" colspan="9"/>
  </tr>
 
  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->vaca_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" colspan="2">
      <?=$this->form->vaca_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->vaca_cod->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->vaca->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td class="label"><?=$this->form->dt_coleta->getLabel();?>:</td>
    <td class="element" colspan="2">
      <?=$this->form->dt_coleta->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"><hr width="95%"></hr></td>
  </tr>
  <tr>
    <td colspan="9">





<div id="tabs" style=" font-size: 12px; width: 850px;">
    <ul>
        <li><a href="#tab1"><span>Dados Gerais</span></a></li>
        <li><a href="#tab2"><span>Inseminações/Montas</span></a></li>
        <li><a href="#tab3"><span>Embriões</span></a></li>
    </ul>
    <div id="tab1">
    <table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 12px;">

  <tr>
    <td height="10" colspan="5"></td>
  </tr>

  <tr>
    <td width="20"></td>
    <td class="label" width="120"><?=$this->form->hormonio->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" width="240">
      <?=$this->form->hormonio->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="10"></td>
    <td class="label" width="140"><?=$this->form->distribuicao->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" width="240">
      <?=$this->form->distribuicao->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>

  </table>
</div>
<div id="tab2">
    <table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 12px;">

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->touro_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->touro_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->touro_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->touro->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <a href="javascript:void(0);" onclick="return showfilter_animal('<?=$this->baseUrl();?>/json/animal','pai');">
        <img alt="" src="<?=$this->baseUrl();?>/images/search.png"/>
      </a>
    </td>
    <td width="50"></td>
  </tr>
  

  <tr>
    <td height="10" colspan="5"></td>
  </tr>




  </table>
  </div>
<div id="tab3">
<table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 12px;">
	<tr>
		<td>





<!-- START OF GENEALOGIA -->


<?php
$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.qtip.js')
	;
?>
<br/>

<table id="genealogia" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td>x</td></tr>
</table>



<!-- END OF GENEALOGIA -->











		</td>
	</tr>
</table>
</div>

</div>
</td></tr>





  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="center">
      <span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="<?=$this->form->getElement('delete')->getAttrib('onclick');?>">
      <span class="UIIcon UIIcon_Delete">&nbsp;</span>
        <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Excluir" name="<?=$this->form->getElement('delete')->getName();?>" id="<?=$this->form->getElement('delete')->getId();?>" onclick="<?=$this->form->getElement('delete')->getAttrib('onclick');?>"/>
      </span>
    </td>
    <td width="10"></td>
    <td align="center">

<span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
<span class="UIIcon UIIcon_Save">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
</span>


<span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"
  onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;"/>
</span>


	</td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>





  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
</form>

<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>

