<?php

/**
 * 
 * @author Abner S. A. Rizzi <abner.rizzi@gmail.com>
 *
 * @version: $Id: json.phtml 7 2010-01-07 18:35:12Z bacteria_ $
 * 
 */

header ( 'Content-Type: text/javascript; charset='.$this->getEncoding().';', true);
header ( 'Expires: Mon, 26 Jul 1997 05:00:00 GMT' );
header ( 'Last-Modified: ' . gmdate('D, d M Y H:i:s' ) . ' GMT');
header ( 'Cache-Control: no-store, no-cache, must-revalidate' );
header ( 'Cache-Control: post-check=0, pre-check=0', false );
header ( 'Pragma: no-cache' );
?>
<?php echo $this->layout()->content ?>