<br/><br/>
<form name="racas" id="racas" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">
 
<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="5" height="20" width="480" style="font-size: 11px;"><b>RACAS</b></td>
  </tr>
 
  <tr>
    <td height="2" bgcolor="#f36400" colspan="5"/>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->dsc->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->dsc->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->sisbov->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->sisbov->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="left" colspan="3">
      <fieldset>
        <legend>Tempo de Gestação (Dias)</legend>
    <table width="100%" align="center" style="border-spacing: 5px;">
      <tr><td>
        <?=$this->form->gestacao_min->getLabel();?>: <?=$this->form->gestacao_min->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      </td><td>
    <?=$this->form->gestacao_med->getLabel();?>: <?=$this->form->gestacao_med->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      </td><td>
    <?=$this->form->gestacao_max->getLabel();?>: <?=$this->form->gestacao_max->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      </td></tr>
    </table>
      </fieldset>
    </td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->idade_repro->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->idade_repro->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->peso_repro->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->peso_repro->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>













 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td colspan="3">

      <table
      	width="100%"
      	style="
      		border: 1px solid;
      		background-color: #000000;
      	"
      	cellpadding="0"
      	cellspacing="0"
      >

        <tr style="height: 32px">
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4;">Idade</td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">0</td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">120</td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">240</td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">365</td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">465</td>
          <td width="10%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">Dias</td>
        </tr>

        <tr style="height: 32px">
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4;">Machos</td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesom1->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesom2->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesom3->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesom4->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesom5->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="10%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">kg</td>
        </tr>

        <tr style="height: 32px">
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4;">Fêmeas</td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesof1->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesof2->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesof3->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesof4->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="15%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">
          <?=$this->form->pesof5->removeDecorator('tag')->removeDecorator('label');?></td>
          <td width="10%" align="center" style="border-bottom: 1px solid; background: #f7f6f4; border-left: 1px solid">kg</td>
        </tr>

      </table>




    </td>
	<td width="50"></td>
  </tr>



  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="left" colspan="3">
      <fieldset>
        <legend>Grupo (Melhoramento Genético USP Pirassununga)</legend>
    <table width="100%" align="center" style="border-spacing: 5px;">
      <tr><td align="center">
    <?=$this->form->grupo->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      </td></tr>
    </table>
      </fieldset>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="left" colspan="3">
      <fieldset>
        <legend>Pode Ser Usada na Composição Sanguínea dos Animais?</legend>
    <table width="100%" align="center" style="border-spacing: 5px;">
      <tr><td align="center">
    <?=$this->form->compsanguinea->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      </td></tr>
    </table>
      </fieldset>
    </td>
    <td width="50"></td>
  </tr>







 
  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
  <tr>
    <td width="20"></td>
    <td align="center">
<span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
<span class="UIIcon UIIcon_Save">&nbsp;</span>
  <input style="display: inline-block;" class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
</span>
    </td>


    <td width="10"></td>
    <td align="center">
<span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"
  />
</span>
    </td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
</form>