<?php
$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/menu.js')
	->appendFile($this->baseUrl() . '/scripts/jquery-1.3.2.js')
	->appendFile($this->baseUrl() . '/scripts/library/parto.js')
	->appendScript('var baseUrl = "' . $this->baseUrl() . '";')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/menu.css');

echo $this->FormEdit($this->form, $this->baseUrl(), $this->elements);
?>