<?php

$this->javascript();

?>
<br/><br/><br/><br/>
<fieldset>
  <legend>Selecione uma fazenda para continuar:</legend>
  <center><br/>
  <form name="form_fazenda" id="form_fazenda" method="post" action="<?=$this->baseUrl() .'/'. $this->action;?>">
    <?=$this->fazenda;?>
    <p align="right">
    <span class="UIButton UIButton_Large UIFormButton  UIButton_Blue">
	  <input style="display: inline-block;" class="UIButton_Text" type="submit" value="Continuar" name="submit"/>
	</span>
	</p>
  </form>
  </center><br/>
</fieldset>
