<?php

$this->javascript();

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.tabs.js')
	;

?>



<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getId();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">

<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="8" height="20" width="480" style="font-size: 11px;"><b><?=str_replace('_', ' ', strtoupper($this->form->getName()));?></b></td>
  </tr>
 
  <tr>
    <td height="2" bgcolor="#f36400" colspan="9"/>
  </tr>
 
  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->fichario_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" colspan="5">
      <?=$this->form->fichario_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->fichario_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->fichario->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <a href="javascript:void(0);" onclick="return showfilter_animal('<?=$this->baseUrl();?>/json/animal','fichario');">
        <img alt="" src="<?=$this->baseUrl();?>/images/search.png"/>
      </a>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->data->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" colspan="5">
      <?=$this->form->data->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->acompanhamento_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" colspan="5">
      <?=$this->form->acompanhamento_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->acompanhamento_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->acompanhamento->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <a href="javascript:void(0);" onclick="return showfilter_acompanhamento('<?=$this->baseUrl();?>/json/acompanhamento','acompanhamento');">
        <img alt="" src="<?=$this->baseUrl();?>/images/search.png"/>
      </a>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->obs->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" colspan="5">
      <?
      $obs = $this->form->obs;
      print '<textarea rows="'.$obs->getAttrib('rows').
      			'" cols="'.$obs->getAttrib('cols').
      			'" class="'.$obs->getAttrib('class').
      			'" id="'.$obs->getId().
      			'" name="'.$obs->getName().
      			'">';
      print $obs->getValue();
      print '</textarea>';
      ?>
    </td>
    <td width="50"></td>
  </tr>


  <tr>
    <td height="10" colspan="9"><hr width="95%"></hr></td>
  </tr>
  <tr>
    <td colspan="9">
	</td>
  </tr>





  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="center"><span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
<span class="UIIcon UIIcon_Save">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
</span></td>
    <td width="10"></td>
    <td align="center"><span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getModuleName() .'/'. Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"
  onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getModuleName() .'/'. Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;"/>
</span></td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>





  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
</form>

<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>
