<?php

//echo $this->FormEdit($this->form, $this->baseUrl(), $this->elements);
//echo $this->form;

$this->javascript();

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.core.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.tabs.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.draggable.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.dialog.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.resizable.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.qtip.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.flexigrid.js')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/flexigrid.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.core.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.datepicker.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.theme.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.tabs.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.dialog.css')
	;


$this->form->getElement('delete')->setAttrib('onclick', "check_delete(".$this->form->getElement('id')->getValue().", '".Zend_Controller_Front::getInstance()->getRequest()->getControllerName()."', '".$this->baseUrl."/".Zend_Controller_Front::getInstance()->getRequest()->getModuleName()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName()."/delete');return false");

?>


<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getId();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">
<?=$this->form->id->removeDecorator('tag')->removeDecorator('label');?>
<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="8" height="20" width="480" style="font-size: 11px;"><b><?=str_replace('_', ' ', strtoupper($this->form->getName()));?></b></td>
  </tr>

  <tr>
    <td height="2" bgcolor="#f36400" colspan="9"/>
  </tr>
 
  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->fazenda_id->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->fazenda_id->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->vaca_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->vaca_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->vaca_cod->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->vaca->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr> 
	<td height="10" colspan="5"> </td> 
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->dt_coleta->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->dt_coleta->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"><hr width="95%"></hr></td>
  </tr>
  <tr>
    <td colspan="9">





<div id="tabs" style="font-size: 12px; width: 850px;">
    <ul>
        <li><a href="#tab1"><span>Inseminações/Montas</span></a></li>
        <li><a href="#tab2"><span>Embriões</span></a></li>
    </ul>
<div id="tab1">
    <table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 11px;">

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td colspan="5">

      <fieldset style="width: 96%;">
        <legend align="left"><b>Inseminações / Montas</b></legend>

        <table
        	align="left"
        	border="0"
        	cellpadding="0"
        	cellspacing="0"
        	bgcolor="#F7F6F4"
        	class="content"
        	style="font-size: 11px;">
          <tr>
          	<td class="label"><?=$this->form->touro_cod->getLabel();?>:</td>
          	<td width="10"></td>
            <td>
              <?=$this->form->touro_id->removeDecorator('tag')->removeDecorator('label');?>
              <?=$this->form->touro_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
              <?=$this->form->touro->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
            </td>
          	<td width="30"></td>
          </tr>
        </table>

        <fieldset style="width: 90%;">
          <legend>1&ordf;</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 11px;">
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
            <tr>
              <td class="label" width="45"><?=$this->form->insemina_dh1d->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh1d->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="55"><?=$this->form->dose1->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->dose1->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="60"><?=$this->form->partida1->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->partida1->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
          </table>
        </fieldset>

      </fieldset>






    </td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>




  </table>
  </div>
<div id="tab2">
<table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 11px;"
				>

  <tr>
    <td width="20"></td>
    <td height="10" colspan="3"></td>
    <td width="20"></td>
  </tr>

  <tr>
    <td></td>
    <td width="300">

        <fieldset style="width: 400px;">
          <legend>Estruturas Avaliadas</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 11px;">
            <tr>
              <td height="10" colspan="7"></td> 
            </tr>
            <tr>
              <td class="label" width="120"><?=$this->form->avalia_od->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->avalia_od->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="120"><?=$this->form->avalia_oe->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->avalia_oe->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="7"></td> 
            </tr>
          </table>
        </fieldset>

    </td>
    <td width="20"></td>
    <td rowspan="5" valign="top" align="center">
























<div id="divGridEmbriao" style="height: 220px; scroll; overflow-x: hidden;">
<table id="emb" cellspacing="0" cellpadding="0" border="0" bgcolor="#f7f6f1" align="center" style="border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(145, 145, 145); -moz-user-select: none;">

<!-- START OF TABLE HEAD -->
	  <tbody>
	  <tr class="head">

 
		  <td width="20" height="20" style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
		  </td>

		  <td width="20" style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
			<b>Embrião</b>
		  </td>

		  <td width="0" style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
			<img src="<?=$this->baseUrl();?>/images/grid/divisor_title.gif" alt=""/>
		  </td>


 
		  <td width="20" height="20" style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
		  </td>

		  <td width="150" style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
			<b>Criador</b>
		  </td>

		  <td width="0" style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
			<img src="<?=$this->baseUrl();?>/images/grid/divisor_title.gif" alt=""/>
		  </td>




		</tr>
<!-- END OF TABLE HEAD -->

<?foreach ($this->embrioes as $embriao):?>

		<tr>
		  <td height="2" bgcolor="#bfbdb3" colspan="12"/>
		</tr>


<tr class="content">
  <td height="2" colspan="12"/>
</tr>

<tr class="content">
  <td height="2" colspan="12"/>
</tr>

<tr class="row1" id="id1">
  <td align="center"></td>
  <td><?=$embriao['embriao'];?></td>
  <td style="background: url('<?=$this->baseUrl();?>/images/grid/divisor_content.gif');"></td>
  <td align="center"></td>
  <td><?=$embriao['criador_cod'];?></td>
</tr>


<tr class="content">
  <td height="4" colspan="12"/>
</tr>


<?endforeach;?>



<tr>
  <td height="10" colspan="12" style='background: url("<?=$this->baseUrl();?>/images/grid/bg_bottom.gif") repeat scroll 0% 0% transparent;'/>
</tr>

</tbody></table>

</div>

    </td>
    <td width="20"></td>
  </tr>

  <tr>
    <td colspan="3">&nbsp;</td>
    <td width="20"></td>
  </tr>





  <tr>
    <td></td>
    <td>

        <fieldset style="width: 400px;">
          <legend>Fecundadas</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 11px;">
            <tr>
              <td height="10" colspan="7"></td> 
            </tr>
            <tr>
              <td class="label" width="120"><?=$this->form->fecundada->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->fecundada->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="120"><?=$this->form->nao_fecundada->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->nao_fecundada->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="7"></td> 
            </tr>
          </table>
        </fieldset>

    </td>
    <td width="20"></td>
    <td width="20"></td>
  </tr>

  <tr>
    <td colspan="3">&nbsp;</td>
    <td width="20"></td>
  </tr>





  <tr>
    <td></td>
    <td>

        <fieldset style="width: 400px;">
          <legend>Estruturas Viáveis</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 11px;">
            <tr>
              <td height="10" colspan="7"></td> 
            </tr>
            <tr>
              <td class="label" width="120"><?=$this->form->viavel->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->viavel->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="120"><?=$this->form->nao_viavel->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->nao_viavel->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="7"></td> 
            </tr>
          </table>
        </fieldset>

    </td>
    <td width="20"></td>
    <td width="20"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>









</table>



</div>

</div>
</td></tr>





  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="center">
      <span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="<?=$this->form->getElement('delete')->getAttrib('onclick');?>">
      <span class="UIIcon UIIcon_Delete">&nbsp;</span>
        <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Excluir" name="<?=$this->form->getElement('delete')->getName();?>" id="<?=$this->form->getElement('delete')->getId();?>"/>
      </span>
    </td>
    <td width="10"></td>
    <td align="center">
      <span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
      <span class="UIIcon UIIcon_Save">&nbsp;</span>
        <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
      </span>

      <span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
      <span class="UIIcon UIIcon_Cancel">&nbsp;</span>
        <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"
          />
      </span>

	</td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>





  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
<?=$this->form->obs->removeDecorator('tag')->removeDecorator('label');?>
</form>

<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>

