<?php

//echo $this->FormEdit($this->form, $this->baseUrl(), $this->elements);
//echo $this->form;

$this->javascript();

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.core.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.tabs.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.draggable.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.dialog.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.resizable.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.qtip.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.flexigrid.js')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/flexigrid.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.core.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.datepicker.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.theme.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.tabs.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.dialog.css')
	;

?>


<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getId();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">
<?=$this->form->id->removeDecorator('tag')->removeDecorator('label');?>
<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('/congado/public/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="8" height="20" width="480" style="font-size: 11px;"><b><?=str_replace('_', ' ', strtoupper($this->form->getName()));?></b></td>
  </tr>

  <tr>
    <td height="2" bgcolor="#f36400" colspan="9"/>
  </tr>
 
  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->vaca_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->vaca_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->vaca_cod->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->vaca->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr> 
	<td height="10" colspan="5"> </td> 
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->dt_coleta->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->dt_coleta->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"><hr width="95%"></hr></td>
  </tr>
  <tr>
    <td colspan="9">





<div id="tabs" style="font-size: 12px; width: 850px;">
    <ul>
        <li><a href="#tab1"><span>Dados Gerais</span></a></li>
        <li><a href="#tab2"><span>Inseminações/Montas</span></a></li>
        <li><a href="#tab3"><span>Embriões</span></a></li>
    </ul>
    <div id="tab1">
    <table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 11px;">

  <tr>
    <td width="20"></td>
    <td height="10" colspan="3"></td>
    <td width="20"></td>
  </tr>

  <tr>
    <td></td>
    <td colspan="3">
      <fieldset style="width: 97%;">
        <legend align="left"><b>Tratamento</b></legend>
        <table
        	align="center"
        	width="100%"
        	border="0"
        	cellpadding="0"
        	cellspacing="0"
        	bgcolor="#F7F6F4"
        	class="content"
        	style="font-size: 11px;">
          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->hormonio->getLabel();?>:</td>
          	<td width="10"></td>
            <td><?=$this->form->hormonio->removeDecorator('tag')->removeDecorator('label');?></td>
            <td width="10"></td>
            <td class="label"><?=$this->form->trata_inicio->getLabel();?>:</td>
            <td width="10"></td>
            <td><?=$this->form->trata_inicio->removeDecorator('tag')->removeDecorator('label');?></td>
            <td width="10"></td>
            <td class="label"><?=$this->form->dosagem->getLabel();?>:</td>
            <td width="10"></td>
            <td><?=$this->form->dosagem->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>

          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
            <td class="label"><?=$this->form->distribuicao->getLabel();?>:</td>
            <td width="10"></td>
            <td><?=$this->form->distribuicao->removeDecorator('tag')->removeDecorator('label');?></td>
            <td width="10"></td>
            <td class="label"><?=$this->form->trata_final->getLabel();?>:</td>
            <td width="10"></td>
            <td><?=$this->form->trata_final->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>
          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>

        </table>
      </fieldset>
    </td>
    <td></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>












  <tr>
    <td></td>
    <td>
      <fieldset style="width: 90%;">
        <legend align="left"><b>Prostaglandina</b></legend>
        <table
        	align="center"
        	width="30%"
        	border="0"
        	cellpadding="0"
        	cellspacing="0"
        	bgcolor="#F7F6F4"
        	class="content"
        	style="font-size: 11px;">
          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->prost_nome->getLabel();?>:</td>
          	<td width="10"></td>
            <td><?=$this->form->prost_nome->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>

          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->prost_dhd->getLabel();?>:</td>
          	<td width="10"></td>
            <td>
              <?=$this->form->prost_dhd->removeDecorator('tag')->removeDecorator('label');?>
              <?=$this->form->prost_dhh->removeDecorator('tag')->removeDecorator('label');?>
            </td>
          </tr>

          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->prost_dosagem->getLabel();?>:</td>
          	<td width="10"></td>
            <td><?=$this->form->prost_dosagem->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>
          <tr>
            <td height="10" colspan="5"> </td> 
          </tr>
        </table>
      </fieldset>
</td><td>
      <fieldset style="width: 90%;">
        <legend align="left"><b>GnRH</b></legend>
        <table
        	align="center"
        	width="30%"
        	border="0"
        	cellpadding="0"
        	cellspacing="0"
        	bgcolor="#F7F6F4"
        	class="content"
        	style="font-size: 12px;">
          <tr>
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->gnrh_nome->getLabel();?>:</td>
          	<td width="10"></td>
            <td><?=$this->form->gnrh_nome->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>

          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->gnrh_dhd->getLabel();?>:</td>
          	<td width="10"></td>
            <td>
              <?=$this->form->gnrh_dhd->removeDecorator('tag')->removeDecorator('label');?>
              <?=$this->form->gnrh_dhh->removeDecorator('tag')->removeDecorator('label');?>
            </td>
          </tr>

          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->gnrh_dosagem->getLabel();?>:</td>
          	<td width="10"></td>
            <td><?=$this->form->gnrh_dosagem->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>
          <tr>
            <td height="10" colspan="5"> </td> 
          </tr>
        </table>
      </fieldset>

</td><td>
      <fieldset style="width: 90%;">
        <legend align="left"><b>Cio Base</b></legend>

        <table
        	align="center"
        	width="30%"
        	border="0"
        	cellpadding="0"
        	cellspacing="0"
        	bgcolor="#F7F6F4"
        	class="content"
        	style="font-size: 12px;">
          <tr>
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->cio_tipo->getLabel();?>:</td>
          	<td width="10"></td>
            <td><?=$this->form->cio_tipo->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>

          <tr> 
            <td height="10" colspan="5"> </td> 
          </tr>
          <tr>
          	<td class="label"><?=$this->form->cio_dhd->getLabel();?>:</td>
          	<td width="10"></td>
            <td>
              <?=$this->form->cio_dhd->removeDecorator('tag')->removeDecorator('label');?>
              <?=$this->form->cio_dhh->removeDecorator('tag')->removeDecorator('label');?>
            </td>
          </tr>
          <tr>
            <td height="10" colspan="5"> </td> 
          </tr>

        </table>

      </fieldset>
    </td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>


















</table>
</div>
<div id="tab2">
    <table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 12px;">

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td colspan="5">

      <fieldset style="width: 96%;">
        <legend align="left"><b>Inseminações / Montas</b></legend>

        <table
        	align="left"
        	border="0"
        	cellpadding="0"
        	cellspacing="0"
        	bgcolor="#F7F6F4"
        	class="content"
        	style="font-size: 12px;">
          <tr>
          	<td class="label"><?=$this->form->touro_cod->getLabel();?>:</td>
          	<td width="10"></td>
            <td>
              <?=$this->form->touro_id->removeDecorator('tag')->removeDecorator('label');?>
              <?=$this->form->touro_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
              <?=$this->form->touro->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
              <a href="javascript:void(0);" onclick="return showfilter_animal('<?=$this->baseUrl();?>/json/animal','pai');">
                <img alt="" src="<?=$this->baseUrl();?>/images/search.png"/>
              </a>
            </td>
          	<td width="30"></td>
          </tr>
        </table>

        <fieldset style="width: 90%;">
          <legend>1&ordf;</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 12px;">
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
            <tr>
              <td class="label" width="45"><?=$this->form->insemina_dh1d->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh1d->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="45"><?=$this->form->insemina_dh1h->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh1h->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="55"><?=$this->form->dose1->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->dose1->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="60"><?=$this->form->partida1->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->partida1->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
          </table>
        </fieldset>

        <fieldset style="width: 90%;">
          <legend>2&ordf;</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 12px;">
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
            <tr>
              <td class="label" width="45"><?=$this->form->insemina_dh2d->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh2d->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="45"><?=$this->form->insemina_dh2h->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh2h->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="55"><?=$this->form->dose2->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->dose2->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="60"><?=$this->form->partida2->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->partida2->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
          </table>
        </fieldset>

        <fieldset style="width: 90%;">
          <legend>3&ordf;</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 12px;">
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
            <tr>
              <td class="label" width="45"><?=$this->form->insemina_dh3d->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh3d->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="45"><?=$this->form->insemina_dh3h->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh3h->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="55"><?=$this->form->dose3->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->dose3->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="60"><?=$this->form->partida3->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->partida3->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
          </table>
        </fieldset>

        <fieldset style="width: 90%;">
          <legend>4&ordf;</legend>
            <table
              align="left"
              border="0"
              cellpadding="0"
              cellspacing="0"
              bgcolor="#F7F6F4"
              class="content"
              style="font-size: 12px;">
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
            <tr>
              <td class="label" width="45"><?=$this->form->insemina_dh4d->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh4d->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="45"><?=$this->form->insemina_dh4h->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->insemina_dh4h->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="55"><?=$this->form->dose4->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->dose4->removeDecorator('tag')->removeDecorator('label');?></td>
              <td width="30"></td>

              <td class="label" width="60"><?=$this->form->partida4->getLabel();?>:</td>
              <td width="10"></td>
              <td><?=$this->form->partida4->removeDecorator('tag')->removeDecorator('label');?></td>
            </tr>
            <tr>
              <td height="10" colspan="16"> </td> 
            </tr>
          </table>
        </fieldset>



      </fieldset>






    </td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>




  </table>
  </div>
<div id="tab3">
<table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 12px;">
	<tr>
		<td>





<!-- START OF GENEALOGIA -->


<table id="genealogia" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td>x</td></tr>
</table>



<!-- END OF GENEALOGIA -->











		</td>
	</tr>
</table>
</div>

</div>
</td></tr>





  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="center">
      <span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="<?=$this->form->getElement('delete')->getAttrib('onclick');?>">
      <span class="UIIcon UIIcon_Delete">&nbsp;</span>
        <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Excluir" name="<?=$this->form->getElement('delete')->getName();?>" id="<?=$this->form->getElement('delete')->getId();?>" onclick="<?=$this->form->getElement('delete')->getAttrib('onclick');?>"/>
      </span>
    </td>
    <td width="10"></td>
    <td align="center">

<span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
<span class="UIIcon UIIcon_Save">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
</span>


<span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"
  onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;"/>
</span>


	</td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>





  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
<?=$this->form->obs->removeDecorator('tag')->removeDecorator('label');?>
</form>

<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>

