<?php

$this->javascript();

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.maskedinput.js')
	->appendFile($this->baseUrl() . '/scripts/library/_filters.js')
	;
	
$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.core.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.datepicker.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.theme.css')
	;

?>

<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getId();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">

<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('/congado/public/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="8" height="20" width="480" style="font-size: 11px;"><b><?=str_replace('_', ' ', strtoupper($this->form->getName()));?></b></td>
  </tr>
 
  <tr>
    <td height="2" bgcolor="#f36400" colspan="9"/>
  </tr>



  <tr>
	<td height="10" colspan="5"> </td>
  </tr>
  <tr>
	<td width="20"></td>
	<td class="label"><?=$this->form->fazenda_id->getLabel();?>:</td>
	<td width="10"></td>
	<td class="element"><?=$this->form->fazenda_id->removeDecorator('tag')->removeDecorator('label');?></td>
	<td width="50"></td>
  </tr>

  <tr>
	<td height="10" colspan="5"></td>
  </tr>
  <tr>
	<td width="20"></td>
	<td class="label"><?=$this->form->data->getLabel();?>:</td>
	<td width="10"></td>
	<td class="element"><?=$this->form->data->removeDecorator('tag')->removeDecorator('label');?></td>
	<td width="50"></td>
  </tr>
 
  <tr>
	<td height="10" colspan="5"> </td>
  </tr>
  <tr>
	<td width="20"></td>
	<td class="label"><?=$this->form->ocorrencia_cod->getLabel();?>:</td>
	<td width="10"></td> 
	<td class="element">
<?=$this->form->ocorrencia_id->removeDecorator('tag')->removeDecorator('label');?>
<?=$this->form->ocorrencia_cod->removeDecorator('tag')->removeDecorator('label');?>
<?=$this->form->ocorrencia->removeDecorator('tag')->removeDecorator('label');?></td>
	<td width="50"></td>
  </tr>



  <tr>
	<td height="10" colspan="5"/>
  </tr>

  <tr>
    <td width="20"></td>
	<td colspan="3">
	  <div id="fichario_grid" style="border: 1px solid; width: 100%;">

<table>
  <tr>
	<td width="20"></td>
	<td class="label" align="left"><?=$this->form->fichario_cod->getLabel();?>:</td>
	<td width="10"></td> 
	<td class="element">
<?=$this->form->fichario_cod->removeDecorator('tag')->removeDecorator('label');?>
	</td>
  </tr>
</table>

<fieldset style="width: 420px;"> 
	<legend style="text-align: left;">Animais</legend>

	<div id="divGridAnimal" style="height: 220px; width: 420px; scroll; overflow-x: hidden;">
	<table id="gridAnimal" border="0" align="center" cellpadding="0" cellspacing="0" style="border-right: 1px solid #CCCCCC; border-left: 1px solid #919191;" bgcolor="#F7F6F1">

<!-- START OF TABLE HEAD -->
	  <tr class="head">

		  <td width="5" style="background: url('/congado/public/images/grid/bg_title.gif');"/>
		  <td width="60" style="background: url('/congado/public/images/grid/bg_title.gif');">
			<a href="javascript:void(0);">Animal</a>
		  </td>

		  <td width="0" style="background: url('/congado/public/images/grid/bg_title.gif');">
			<img src="/congado/public/images/grid/divisor_title.gif" alt=""/>
		  </td>

		  <td width="15" style="background: url('/congado/public/images/grid/bg_title.gif');"/>
		  <td width="150" style="background: url('/congado/public/images/grid/bg_title.gif');">
			<a href="javascript:void(0);">Nome</a>
		  </td>

		  <td width="0" style="background: url('/congado/public/images/grid/bg_title.gif');">
			<img src="/congado/public/images/grid/divisor_title.gif" alt=""/>
		  </td>

		  <td width="5" style="background: url('/congado/public/images/grid/bg_title.gif');"/>
          <td width="80" style="background: url('/congado/public/images/grid/bg_title.gif');">
            <a href="javascript:void(0);">Horário</a>
          </td>

          <td width="0" style="background: url('/congado/public/images/grid/bg_title.gif');">
			<img src="/congado/public/images/grid/divisor_title.gif" alt=""/>
		  </td>

		  <td width="5" style="background: url('/congado/public/images/grid/bg_title.gif');"/>
          <td width="70" style="background: url('/congado/public/images/grid/bg_title.gif');" align="center">
            <a href="javascript:void(0);">Remover</a>
          </td>

          <td width="0" style="background: url('/congado/public/images/grid/bg_title.gif');">
			<img src="/congado/public/images/grid/divisor_title.gif" alt=""/>
		  </td>

		</tr>
<!-- END OF TABLE HEAD -->


<?if (is_array($this->animais)):?>
<?for($i=0; $i < count($this->animais); $i++):?>
<?$animal = $this->animais[$i];?>

<?
// Se nao for o primeiro registro
if ($i==0){?>
<tr class="content"><td height="2" colspan="12"></td></tr>
<?}?>
<tr><td height="1" colspan="12" bgcolor="#BFBDB3"></td></tr>
<tr class="content">
  <td height="2" colspan="12"></td>
</tr>
			
<tr class="row1" id="id<?=$animal['id'];?>">
  <td/>
  <td><?=$animal['cod'];?></td>
  <td style="background: url('/congado/public/images/grid/divisor_content.gif');"></td>

  <td/>
  <td align="left"><?=$animal['nome'];?></td>
  <td style="background: url('/congado/public/images/grid/divisor_content.gif');"></td>

  <td/>
  <td align="left" style="padding-left: 10px;"><?=$animal['time'];?></td>
  <td style="background: url('/congado/public/images/grid/divisor_content.gif');"></td> 

  <td/>
  <td align="center">
    <input type="hidden" name="fichario[]" value="<?=$animal['id'];?>">
    <input type="hidden" name="horario[<?=$animal['id'];?>]" value="<?=$animal['time'];?>">
    <a class="UIObjectListing_RemoveLink" href="javascript:void(0);" onclick="deleteAnimal(<?=$animal['id'];?>);">&nbsp;</a>
  </td>
  <td/> 
</tr> 


<?endfor;?>
<?endif;?>


<tr id="lastRow" class="content">
  <td colspan="12" height="4"></td>
</tr>

<tr>
  <td height="10" colspan="12" style="background: url('/congado/public/images/grid/bg_bottom.gif');"></td>
</tr>

</table>
</div>
<br/>
</fieldset>
<br/>
      </div>
    </td>
	<td width="50"></td>
  </tr>

  <tr>
	<td height="10" colspan="12"/>
  </tr>

  <tr>
	<td width="20"></td>

	<td align="center">

	</td>
	<td width="10"></td>
	<td align="center">
<span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#controle_sanitario__preventivo').submit();">
<span class="UIIcon UIIcon_Save">&nbsp;</span>
  <input style="display: inline-block;" class="UIButton_Text" type="submit" value="Salvar" name="submit_" id="submit_"/>
</span>


<span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '/congado/public/movimentacao/sanitariopreventivo'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="cancel" id="cancel" onclick="location.href = '/congado/public/movimentacao/sanitariopreventivo'; return false;"/>
</span>

    </td>
	<td width="50"></td>
  </tr>

  <tr>
	<td height="10" colspan="5"/>
  </tr>

</table>
</form>


<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>

<div id="error" style="display: none;"></div>