<?php

$this->headScript()
	->appendScript("\t__title = 'Controle Sanitário - Preventivo';\n")
	->appendScript("\t__module = '".Zend_Controller_Front::getInstance()->getRequest()->getModuleName()."';\n")
//	->appendFile($this->baseUrl() . '/scripts/library/default_search.js')
	->appendFile($this->baseUrl() . '/scripts/library/movimentacao/preventivo_search.js')
	;

echo $this->grid($this->grid);

// Quando ela perguntar "Foi gostoso?" Diga Não se preocupe comigo…eu estou bem, eu juro...
?>

