<?php

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.maskedinput.js')
	->appendFile($this->baseUrl() . '/scripts/library/estacaomonta.js')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.core.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.datepicker.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.theme.css')
    ;

echo $this->FormEdit($this->form, $this->baseUrl(), $this->elements);

?>
