<?php echo $this->doctype() ?>

<html <?php echo 'xmlns="http://www.w3.org/1999/xhtml"'?>>
  <head>
    <meta http-equiv="Content-type" content="text/html;charset=<?php echo $this->getEncoding() ?>" />
    <?php
//    if ($this->title) {
//    	echo $this->headTitle()->append($this->title);
//    } else {
    	echo $this->headTitle();
//    }
    ?>

    <?php echo $this->headLink() ?>

    <?php echo $this->headStyle() ?>

  </head>

<body>
	<?php echo $this->layout()->content ?>

<?php echo $this->headScript() ?>

<?php echo $this->bundleScript() ?>

</body>
</html>