<table width="100%" height="400" border="0">
  <tr><td valign="middle" align="center">
  <div class="ok">
    <img src="<?=$this->baseUrl();?>/images/ok.png" alt="" border="0"/>
    <br/><br/>
    Dados alterados com sucesso.
  </div>
  <br/>
  <div class="warning">
    <img src="<?=$this->baseUrl();?>/images/exclamation.png" alt="" border="0"/>
    <br/><br/>
    Para que as alterações tenham efeito, é necessário efetuar o login novamente.
    <br/><br/>
    <a href="<?=$this->baseUrl();?>/auth/logout">Clique aqui para sair</a>.
  </div>
  </td></tr>
</table>