<html>

<script type="text/javascript" src="<?=$this->baseUrl();?>/scripts/library/jquery/jquery.fcbkcomplete.js"></script>
<link rel="stylesheet" href="<?=$this->baseUrl();?>/styles/jquery/fcbkcomplete.css" type="text/css" media="screen" title="Test Stylesheet" charset="utf-8" />

<script language="JavaScript">
        $(document).ready(function() 
        {        
          
          $("#select2").fcbkcomplete({
            json_url: "<?=$this->baseUrl();?>/json/fcbk",
            filter_case: false,
            filter_hide: true,
			firstselected: true,
            filter_selected: true,
			maxitems: 5,
            newel: true        
          });		 
        });
		
		function testme(item)
	  	{	if ($.browser.mozilla) 
			{
				console.log(item);
			}
			else
			{
				alert(item);
			}		  	
	  	}    
    </script>

    
    <select id="select2" name="select2"></select>
    </html>