<?
$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/fcbk/eARZq_C-Mf4.css')
	->appendStylesheet($this->baseUrl() . '/styles/fcbk/DKM6CTLqpIp.css')
;

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/fcbk/71qWoI8S5cd.js')
	->appendFile($this->baseUrl() . '/scripts/library/fcbk/845Rh0B0Eja.js')
	->appendFile($this->baseUrl() . '/scripts/library/fcbk/9GiaWrLK1HF.js')
	->appendFile($this->baseUrl() . '/scripts/library/fcbk/ltal48w7Cfq.js')
	->appendFile($this->baseUrl() . '/scripts/library/fcbk/PbD_CkDvn44.js')
	->appendFile($this->baseUrl() . '/scripts/library/fcbk/JOa9lR4Aorn.js')
;
?>


<div class="mbm pam uiBoxGray topborder">
  <div class="clearfix editFriendsSearchHeader">
    <div class="clearfix">
<div class="uiSelector lfloat uiSelectorNormal uiSelectorDynamicLabel" id="u850684_12">
<div class="wrap"><a class="uiSelectorButton uiButton" href="#" role="button" aria-haspopup="1" data-length="30" rel="toggle">
<i class="mrs img sp_epwws3 sx_61e291"></i>
<span class="uiButtonText">Recently Interacted</span></a>
<div class="uiSelectorMenuWrapper uiToggleFlyout">
<ul role="menu" class="uiMenu uiSelectorMenu">
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="All Friends"><a class="itemAnchor" role="menuitemradio"
		tabindex="0" aria-checked="false" href="#" rel="ignore"><span
		class="itemLabel fsm">All Friends</span></a></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption checked"
		data-label="Recently Interacted"><a class="itemAnchor"
		role="menuitemradio" tabindex="-1" aria-checked="true" href="#"
		rel="ignore"><span class="itemLabel fsm">Recently Interacted</span></a></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="Recently Added"><a class="itemAnchor" role="menuitemradio"
		tabindex="-1" aria-checked="false" href="#" rel="ignore"><span
		class="itemLabel fsm">Recently Added</span></a></li>
	<li class="uiMenuSeparator"></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="Goiânia"><a class="itemAnchor" role="menuitemradio"
		tabindex="-1" aria-checked="false" href="#" rel="ignore"><span
		class="itemLabel fsm">Goiânia</span></a></li>
	<li class="uiMenuSeparator"></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="Search by Current City"><a class="itemAnchor"
		role="menuitemradio" tabindex="-1" aria-checked="false" href="#"
		rel="ignore"><span class="itemLabel fsm">Search by Current City</span></a></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="Search by Hometown"><a class="itemAnchor"
		role="menuitemradio" tabindex="-1" aria-checked="false" href="#"
		rel="ignore"><span class="itemLabel fsm">Search by Hometown</span></a></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="Search by School"><a class="itemAnchor"
		role="menuitemradio" tabindex="-1" aria-checked="false" href="#"
		rel="ignore"><span class="itemLabel fsm">Search by School</span></a></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="Search by Workplace"><a class="itemAnchor"
		role="menuitemradio" tabindex="-1" aria-checked="false" href="#"
		rel="ignore"><span class="itemLabel fsm">Search by Workplace</span></a></li>
	<li class="uiMenuItem uiMenuItemRadio uiSelectorOption"
		data-label="Search by Interest"><a class="itemAnchor"
		role="menuitemradio" tabindex="-1" aria-checked="false" href="#"
		rel="ignore"><span class="itemLabel fsm">Search by Interest</span></a></li>
</ul>
</div>
</div>

<select id="qwe">
	<option value=""></option>
	<option value="all">All Friends</option>
	<option value="recent" selected="1">Recently Interacted</option>
	<option value="new">Recently Added</option>
	<option value="location_113400028670072">Goiânia</option>
	<option value="currentcity">Search by Current City</option>
	<option value="hometown">Search by Hometown</option>
	<option value="school">Search by School</option>
	<option value="workplace">Search by Workplace</option>
	<option value="interest">Search by Interest</option>
</select></div>
</div>
</div>
</div>


