<?php

$this->javascript();

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.center.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.dimensions.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.flexigrid.js')
	->appendFile($this->baseUrl() . '/scripts/library/_filters.js')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/flexigrid.css')
	;

?>


<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getName();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">
<?=$this->form->id->removeDecorator('tag')->removeDecorator('label');?>
<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="5" height="20" width="480" style="font-size: 11px;"><b><?=str_replace('_', ' ', strtoupper($this->form->getName()));?></b></td>
  </tr>
 
  <tr>
    <td height="2" bgcolor="#f36400" colspan="5"/>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->raca_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->raca_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->raca_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->raca->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->pai_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->pai_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->pai_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->pai->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->mae_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->mae_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->mae_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->mae->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->cria_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->cria_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->cria_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->cria->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>

  <tr>
    <td width="20"></td>
    <td align="center">
<span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="<?=$this->form->getElement('delete')->getAttrib('onclick');?>">
<span class="UIIcon UIIcon_Delete">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Excluir" name="<?=$this->form->getElement('delete')->getName();?>" id="<?=$this->form->getElement('delete')->getId();?>" onclick="<?=$this->form->getElement('delete')->getAttrib('onclick');?>"/>
</span>
    </td>
    <td width="10"></td>
    <td align="center">
<span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
<span class="UIIcon UIIcon_Save">&nbsp;</span>
  <input style="display: inline-block;" class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
</span>

<span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"
  onclick="location.href = '<?=$this->baseUrl."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;"/>
</span>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>





  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
</form>



<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>
