INSERT INTO congado.doenca VALUES(null, "01","AFTOSA",false,false,false,false,true,false,false,false,false,false,true,false,true,true,0,200,);
INSERT INTO congado.doenca VALUES(null, "99","VACINA AFTOSA",true,true,true,true,true,true,true,true,true,true,true,true,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "AR","AVALIAÇÃO REPRODUTIVA",false,false,false,false,false,false,false,false,false,false,false,false,false,true,,,);
INSERT INTO congado.doenca VALUES(null, "BR","BRUCELOSE",false,false,false,false,false,false,false,false,false,false,false,false,false,true,3,8,);
INSERT INTO congado.doenca VALUES(null, "CA","CASQUIAMENTO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CB","CIRUGIA UMBIGO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CE","CERATO/CONJUNTIVITE",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CI","CIOSIN",false,false,false,false,false,false,false,false,false,false,false,false,false,true,,,);
INSERT INTO congado.doenca VALUES(null, "CJ","CASQUIAMENTO- JOAQUIM CORDEIRO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CL","CLOSTRIDIOSE",false,true,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CM","IBR/BVD/LEPTOSPIROSE",false,true,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CO","CORPO LUTEO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CP","CASQUEAMENTO PREVENTIVO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CS","CISTO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CT","CONTEUDO UTERINO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "CZ","CASQUIAMENTO -- ZÉ GANCHO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "DI","DIARREIA",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "DS","DIARREIA DE SANGUE",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "FR","FRAQUEZA",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "IC","IMPLANTE PARA CIO",false,false,false,false,false,false,false,false,false,false,false,false,false,true,,,);
INSERT INTO congado.doenca VALUES(null, "IF","INFECÇÃO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "IN","INTOXICAÇÃO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "IP","INFECÇÃO PÉ",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "IT","INFECÇÃO UTERINA",false,false,false,false,false,false,false,false,false,false,false,false,false,true,,,);
INSERT INTO congado.doenca VALUES(null, "IU","INFECÇÃO NO UMBIGO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "MD","MAO DESLOCADA",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "MI","MÃO INCHADA",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "PC","PICADA CARCARÁ",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "PE","PERNAS E REGIAO VENTRAL INCHAD",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "PH","MUDANÇA PH UTERINO",false,false,false,false,false,false,false,false,false,false,false,false,false,true,,,);
INSERT INTO congado.doenca VALUES(null, "PI","PE INCHADO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "PN","PNEUMONIA",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "PO","CIRURGIA DE PROLÓPIO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "RP","RETENÇÃO PLACENTA",false,false,false,false,false,false,false,false,false,false,false,false,false,true,,,);
INSERT INTO congado.doenca VALUES(null, "TR","TRISTEZINHA",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
INSERT INTO congado.doenca VALUES(null, "UI","UMBIGO INCHADO",false,false,false,false,false,false,false,false,false,false,false,false,true,true,,,);
