<?php

$this->javascript();

?>

<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getId();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">

<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('<?=$this->baseUrl();?>/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="8" height="20" width="480" style="font-size: 11px;"><b><?=str_replace('_', ' ', strtoupper($this->form->getName()));?></b></td>
  </tr>
 
  <tr>
    <td height="2" bgcolor="#f36400" colspan="9"/>
  </tr>
 
  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" colspan="5">
      <?=$this->form->cod->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

 
  <tr>
    <td height="10" colspan="9"><hr width="95%"></hr></td>
  </tr>
  <tr>
    <td colspan="9">





<div id="tabs" style=" font-size: 12px; width: 850px;">
    <ul>
        <li><a href="#fragment-1"><span>Dados Básicos</span></a></li>
        <li><a href="#fragment-2"><span>Filiação / Obs.</span></a></li>
    </ul>
    <div id="fragment-1">
    <table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 12px;">

  <tr>
    <td height="10" colspan="5"></td>
  </tr>

  <tr>
    <td width="20"></td>
    <td class="label" width="120"><?=$this->form->nome->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" width="240">
      <?=$this->form->nome->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="10"></td>
    <td class="label" width="140"><?=$this->form->rgn->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" width="240">
      <?=$this->form->rgn->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->sisbov->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->sisbov->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="20"></td>
    <td class="label"><?=$this->form->dt_nascimento->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->dt_nascimento->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->criador_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->criador_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->criador_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->criador->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="20"></td>
    <td class="label"><?=$this->form->pelagem_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->pelagem_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->pelagem_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->pelagem->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->raca_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->raca_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->raca_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->raca->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="20"></td>
    <td class="label"><?=$this->form->rebanho_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->rebanho_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->rebanho_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->rebanho->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="9"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->categoria_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->categoria_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->categoria_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->categoria->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="20"></td>
    <td class="label"><?=$this->form->local_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->local_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->local_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->local->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label">Grau de Sangue:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->grausangue_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->grausangue_manual->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->grausangue_manual->getLabel();?><br/>
      <?=$this->form->grausangue_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->grausangue->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="20"></td>
    <td class="label"><?=$this->form->sexo->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->sexo->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->origem->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element" colspan="5">
      <?=$this->form->origem->removeDecorator('tag')->removeDecorator('label');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>

  </table>
</div>
<div id="fragment-2">
    <table
		align="center"
		width="800"
		border="0"
		cellpadding="0"
		cellspacing="0"
		bgcolor="#F7F6F4"
		class="content"
		style="	border-right: 1px solid #CCCCCC;
				border-bottom: 1px solid #CCCCCC;
				border-left: 1px solid #919191;
				border-top: 1px solid #919191;
				font-size: 12px;">

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->pai_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->pai_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->pai_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->pai->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>
  
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->mae_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->mae_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->mae_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->mae->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->receptora_cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?=$this->form->receptora_id->removeDecorator('tag')->removeDecorator('label');?>
      <?=$this->form->receptora_cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
      <?=$this->form->receptora->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->obs->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element">
      <?
      $obs = $this->form->obs;
      print '<textarea rows="'.$obs->getAttrib('rows').
      			'" cols="'.$obs->getAttrib('cols').
      			'" class="'.$obs->getAttrib('class').
      			'" id="'.$obs->getId().
      			'" name="'.$obs->getName().
      			'">';
      print $obs->getValue();
      print '</textarea>';
      ?>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>




  </table>
  </div>
</div>
</td></tr>





  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="center"><span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
<span class="UIIcon UIIcon_Save">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
</span></td>
    <td width="10"></td>
    <td align="center"><span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"/>
</span></td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>





  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
</form>

<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>
