<?php
$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.qtip.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.core.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.draggable.js')
	->appendFile($this->baseUrl() . '/scripts/library/genealogia.js')
	;
?>
<br/>

<table border="0" align="center" cellpadding="0" cellspacing="0">

	<tr>

<?if (@$this->array['id']):?>
	  <td class="animal" rowspan="15"><a href="javascript:void(0);" id="a<?=$this->array['id'];?>"><?=$this->array['cod'];?><br/><?=$this->array['nome'];?></a></td>
<?else:?>
	  <td class="vazio" rowspan="15">Desconhecido</td>
<?endif;?>

	  <td width="10" rowspan="15"></td>
<?if (@$this->array['pai']['id'] != ""):?>
	  <td class="animalm" rowspan="7"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['pai']['id'];?>" id="a<?=$this->array['pai']['id'];?>"><?=$this->array['pai']['cod'];?><br/><?=$this->array['pai']['nome'];?></a></td>
<?else:?>
	  <td class="vazio" rowspan="7">Desconhecido</td>
<?endif;?>

	  <td width="10" rowspan="15"></td>
<?if (@$this->array['pai']['pai']['id']):?>
	  <td class="animalm" rowspan="3"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['pai']['pai']['id'];?>" id="a<?=$this->array['pai']['pai']['id'];?>"><?=$this->array['pai']['pai']['cod'];?><br/><?=$this->array['pai']['pai']['nome'];?></a></td>
<?else:?>
	  <td class="vazio" rowspan="3">Desconhecido</td>
<?endif;?>

	  <td width="10" rowspan="15"></td>
<?if (@$this->array['pai']['pai']['pai']['id']):?>
	  <td class="animalm"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['pai']['pai']['pai']['id'];?>" id="a<?=$this->array['pai']['pai']['pai']['id'];?>"><?=$this->array['pai']['pai']['pai']['cod'];?><br/><?=$this->array['pai']['pai']['pai']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>

	</tr>

	<tr>
	  <td style="height: 5px;"></td>
	</tr>

	<tr>

<?if (@$this->array['pai']['pai']['mae']['id']):?>
	  <td class="animalf"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['pai']['pai']['mae']['id'];?>" id="a<?=$this->array['pai']['pai']['mae']['id'];?>"><?=$this->array['pai']['pai']['mae']['cod'];?><br/><?=$this->array['pai']['pai']['mae']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>


	</tr>


	<tr>
	  <td style="height: 10px;"></td>
	</tr>


	<tr>

<?if (@$this->array['pai']['mae']['id'] != ""):?>
	  <td class="animalf" rowspan="3"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['pai']['mae']['id'];?>" id="a<?=$this->array['pai']['mae']['id'];?>"><?=$this->array['pai']['mae']['cod'];?><br/><?=$this->array['pai']['mae']['nome'];?></a></td>
<?else:?>
	  <td class="vazio" rowspan="3">Desconhecido</td>
<?endif;?>

<?if (@$this->array['pai']['mae']['pai']['id']):?>
	  <td class="animalm"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['pai']['mae']['pai']['id'];?>" id="a<?=$this->array['pai']['mae']['pai']['id'];?>"><?=$this->array['pai']['mae']['pai']['cod'];?><br/><?=$this->array['pai']['mae']['pai']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>


	</tr>


	<tr>
	  <td style="height: 5px;"></td>
	</tr>


	<tr>

<?if (@$this->array['pai']['mae']['mae']['id']):?>
	  <td class="animalf"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['pai']['mae']['mae']['id'];?>" id="a<?=$this->array['pai']['mae']['mae']['id'];?>"><?=$this->array['pai']['mae']['mae']['cod'];?><br/><?=$this->array['pai']['mae']['mae']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>


	</tr>


	<tr>
	  <td style="height: 10px;"></td>
	</tr>


	<tr>

<?if (@$this->array['mae']['id'] != ""):?>
	  <td class="animalf" rowspan="7"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['mae']['id'];?>" id="a<?=$this->array['mae']['id'];?>"><?=$this->array['mae']['cod'];?><br/><?=$this->array['mae']['nome'];?></a></td>
<?else:?>
	  <td class="vazio" rowspan="7">Desconhecido</td>
<?endif;?>
<?if (@$this->array['mae']['pai']['id'] != ""):?>
	  <td class="animalm" rowspan="3"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['mae']['pai']['id'];?>" id="a<?=$this->array['mae']['pai']['id'];?>"><?=$this->array['mae']['pai']['cod'];?><br/><?=$this->array['mae']['pai']['nome'];?></a></td>
<?else:?>
	  <td class="vazio" rowspan="3">Desconhecido</td>
<?endif;?>
<?if (@$this->array['mae']['pai']['pai']['id']):?>
	  <td class="animalm"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['mae']['pai']['pai']['id'];?>" id="a<?=$this->array['mae']['pai']['pai']['id'];?>"><?=$this->array['mae']['pai']['pai']['cod'];?><br/><?=$this->array['mae']['pai']['pai']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>


	</tr>


	<tr>
	  <td style="height: 5px;"></td>
	</tr>


	<tr>

<?if (@$this->array['mae']['pai']['mae']['id']):?>
	  <td class="animalf"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['mae']['pai']['mae']['id'];?>" id="a<?=$this->array['mae']['pai']['mae']['id'];?>"><?=$this->array['mae']['pai']['mae']['cod'];?><br/><?=$this->array['mae']['pai']['mae']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>


	</tr>


	<tr>
	  <td style="height: 10px;"></td>
	</tr>


	<tr>

<?if (@$this->array['mae']['mae']['id'] != ""):?>
	  <td class="animalf" rowspan="3"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['mae']['mae']['id'];?>" id="a<?=$this->array['mae']['mae']['id'];?>"><?=$this->array['mae']['mae']['cod'];?><br/><?=$this->array['mae']['mae']['nome'];?></a></td>
<?else:?>
	  <td class="vazio" rowspan="3">Desconhecido</td>
<?endif;?>
	  <?if (@$this->array['mae']['mae']['pai']['id']):?>
	  <td class="animalm"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['mae']['mae']['pai']['id'];?>" id="a<?=$this->array['mae']['mae']['pai']['id'];?>"><?=$this->array['mae']['mae']['pai']['cod'];?><br/><?=$this->array['mae']['mae']['pai']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>
	  


	</tr>


	<tr>
	  <td style="height: 5px;"></td>
	</tr>


	<tr>

<?if (@$this->array['mae']['mae']['mae']['id']):?>
	  <td class="animalf"><a href="<?=$this->baseUrl() . "/fichario/genealogia/id/" . $this->array['mae']['mae']['mae']['id'];?>" id="a<?=$this->array['mae']['mae']['mae']['id'];?>"><?=$this->array['mae']['mae']['mae']['cod'];?><br/><?=$this->array['mae']['mae']['mae']['nome'];?></a></td>
<?else:?>
	  <td class="vazio">Desconhecido</td>
<?endif;?>


	</tr>

</table>

