<?php

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/fichario_search.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.core.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.draggable.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.dialog.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.bigframe.js')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.all.css')
	;

echo $this->grid($this->grid);

?>

<div class="demo">
<div id="dialog" title="Basic dialog" style="font-size: 12px;"> 
	<p>This is the default dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the 'x' icon.</p> 
</div>
</div>