<?php

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/fichario_search.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.core.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.draggable.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.dialog.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.bigframe.js')
	;

$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.all.css')
	;

echo $this->grid($this->grid);

?>
