<br/><br/>
<form name="<?=$this->form->getName();?>" id="<?=$this->form->getName();?>" action="<?=$this->baseUrl . $this->form->getAction();?>" method="post">
 
<table
	id="form"
	align="center"
	border="0"
	cellpadding="0"
	cellspacing="0"
	bgcolor="#F7F6F4"
	class="content"
	style="	border-right: 1px solid #CCCCCC;
			border-bottom: 1px solid #CCCCCC;
			border-left: 1px solid #919191;
			font-size: 12px;">

  <tr style="background: url('/congado/public/images/grid/bg_title.gif');">
    <td width="20" ></td>
    <td colspan="5" height="20" width="480" style="font-size: 11px;"><b>RACAS</b></td>
  </tr>
 
  <tr>
    <td height="2" bgcolor="#f36400" colspan="5"/>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->cod->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->cod->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->dsc->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->dsc->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>
 
  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td align="left" colspan="3">
    <table>
      <tr>
        <td width="50%" rowspan="2">
          <fieldset style="width: 240px;">
            <legend>Período</legend>
                <table width="100%" align="center" style="border-spacing: 5px;">

                  <tr><td>
                    <?=$this->form->jan->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->jan->getLabel();?>
                  </td><td>
                    <?=$this->form->jul->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->jul->getLabel();?>
                  </td></tr>

                  <tr><td>
                    <?=$this->form->fev->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->fev->getLabel();?>
                  </td><td>
                    <?=$this->form->ago->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->ago->getLabel();?>
                  </td></tr>

                  <tr><td>
                    <?=$this->form->mar->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->mar->getLabel();?>
                  </td><td>
                    <?=$this->form->set->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->set->getLabel();?>
                  </td></tr>

                  <tr><td>
                    <?=$this->form->abr->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->abr->getLabel();?>
                  </td><td>
                    <?=$this->form->out->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->out->getLabel();?>
                  </td></tr>

                  <tr><td>
                    <?=$this->form->mai->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->mai->getLabel();?>
                  </td><td>
                    <?=$this->form->nov->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->nov->getLabel();?>
                  </td></tr>

                  <tr><td>
                    <?=$this->form->jun->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->jun->getLabel();?>
                  </td><td>
                    <?=$this->form->dez->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->dez->getLabel();?>
                  </td></tr>

                </table>
          </fieldset>
        </td>

        <td width="50%" height="50%" valign="top">
          <fieldset style="width: 240px;">
            <legend>Sexo</legend>
        <table width="100%" align="center" style="border-spacing: 5px;">
          <tr>
            <td>
              <?=$this->form->macho->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->macho->getLabel();?><br/>
              <?=$this->form->femea->removeDecorator('tag')->removeDecorator('label');?> <?=$this->form->femea->getLabel();?>
            </td>
          </tr>
        </table>
          </fieldset>
        </td>
        </tr>
        
        <tr>
		<td width="50%" height="50%" valign="bottom">
          <fieldset style="width: 240px;">
            <legend>Idade (em Meses)</legend>
        <table width="100%" align="center" style="border-spacing: 5px;">
          <tr>
            <td><?=$this->form->idadeInicio->getLabel();?>:</td>
            <td><?=$this->form->idadeInicio->removeDecorator('tag')->removeDecorator('label');?></td>
          </tr>
          <tr>
			<td><?=$this->form->idadeFinal->getLabel();?></td>
			<td><?=$this->form->idadeFinal->removeDecorator('tag')->removeDecorator('label');?></td>
		  </tr> 
        </table>
          </fieldset>
        </td>

      </tr>
    </table>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"></td>
  </tr>
  <tr>
    <td width="20"></td>
    <td class="label"><?=$this->form->dia->getLabel();?>:</td>
    <td width="10"></td>
    <td class="element"><?=$this->form->dia->removeDecorator('tag')->removeDecorator('label')->removeFilter('StringTrim');?></td>
    <td width="50"></td>
  </tr>


  <tr>
    <td height="10" colspan="5"/>
  </tr>

  <tr>
    <td width="20"></td>
    <td align="center">
	<span class="UIButton UIButton_Large UIFormButton  UIButton_Blue" onclick="$('#<?=$this->form->getName();?>').submit();">
	<span class="UIIcon UIIcon_Save">&nbsp;</span>
	  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Salvar" name="<?=$this->form->getElement('submit')->getName();?>_" id="<?=$this->form->getElement('submit')->getId();?>_"/>
	</span>
    </td>
    <td width="10"></td>
    <td align="center">
<span class="UIButton UIButton_Large UIFormButton  UIButton_Gray" onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;">
<span class="UIIcon UIIcon_Cancel">&nbsp;</span>
  <input style="display: inline-block;"  class="UIButton_Text" type="button" value="Cancelar" name="<?=$this->form->getElement('cancel')->getName();?>" id="<?=$this->form->getElement('cancel')->getId();?>"
  onclick="location.href = '<?=$this->baseUrl()."/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>'; return false;"/>
</span>
    </td>
    <td width="50"></td>
  </tr>

  <tr>
    <td height="10" colspan="5"/>
  </tr>





  <tr>
    <td height="10" colspan="5"/>
  </tr>
 
</table>
</form>