<?php

$this->javascript();

$this->headScript()
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.ui.datepicker.js')
	->appendFile($this->baseUrl() . '/scripts/library/jquery/jquery.maskedinput.js')
	->appendFile($this->baseUrl() . '/scripts/library/_filters.js')
	;
	
$this->headLink()
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.core.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.datepicker.css')
	->appendStylesheet($this->baseUrl() . '/styles/jquery/ui.theme.css')
	;

echo $this->FormEdit($this->form, $this->baseUrl(), $this->elements);

?>

<div id="dlg" style="display: none;">
  <div id="dlg-grid" style="padding: 0px; margin: 0px"></div>
</div>
